#!/bin/bash

##dir pos
for f in 13 15 17 24 26 28 35 37 46 48 55 57 66 68 77 88 

do 

cat > make_fit_$f-dir <<EOF
set encoding utf8
set terminal postscript eps enhanced color solid "Times-Roman" 20
set output 'Fit-D$f-dir.eps'

FIT_LIMIT=1.0e-18

set xrange [0.999998e-9:3.0000001e-9]
set yrange [0.999998e-9:3.0000001e-9]
#set zrange [1e-6:*]

set logscale z

d2=1
d3=2
d4=2

f4(x,y) =  d1+(d2/((x*10**9)**d3*(y*10**9)**d4))

fit f4(x,y) 'D$f-dir.dat' u (\$1):(\$2):(\$3) via d1,d2,d3,d4

splot 'D$f-dir.dat' u (\$1):(\$2):3 w l lw 3 t 'Theo.',  \
f4(x,y) w l t 'Fit'

EOF

gnuplot make_fit_$f-dir 2> gnufit_$f-dir

grep -E  'd1.*+/-' gnufit_$f-dir | awk '{print "a'$f'_1e =", $3}' >> Parameters-dir.dat 
grep -E  'd2.*+/-' gnufit_$f-dir | awk '{print "a'$f'_2e =", $3}' >> Parameters-dir.dat 
grep -E  'd3.*+/-' gnufit_$f-dir | awk '{print "a'$f'_3e =", $3}' >> Parameters-dir.dat 
grep -E  'd4.*+/-' gnufit_$f-dir | awk '{print "a'$f'_4e =", $3}' >> Parameters-dir.dat

echo "$f dir DONE"

done

##exc pos
for f in 13 15 17 24 26 28 35 37 46 48 55 57 66 68 77 88 

do 

cat > make_fit_$f-ex <<EOF
set encoding utf8
set terminal postscript eps enhanced color solid "Times-Roman" 20
set output 'Fit-D$f-ex.eps'

FIT_LIMIT=1.0e-18

set xrange [0.999998e-9:3.0000001e-9]
set yrange [0.999998e-9:3.0000001e-9]
#set zrange [1e-6:*]

set logscale z

d2=1
d3=2
d4=2

f4(x,y) =  d1+(d2/((x*10**9)**d3*(y*10**9)**d4))

fit f4(x,y) 'D$f-ex.dat' u (\$1):(\$2):(\$3) via d1,d2,d3,d4

splot 'D$f-ex.dat' u (\$1):(\$2):3 w l lw 3 t 'Theo.',  \
f4(x,y) w l t 'Fit'

EOF

gnuplot make_fit_$f-ex 2> gnufit_$f-ex

grep -E  'd1.*+/-' gnufit_$f-ex | awk '{print "a'$f'_1e =", $3}' >> Parameters-ex.dat 
grep -E  'd2.*+/-' gnufit_$f-ex | awk '{print "a'$f'_2e =", $3}' >> Parameters-ex.dat 
grep -E  'd3.*+/-' gnufit_$f-ex | awk '{print "a'$f'_3e =", $3}' >> Parameters-ex.dat 
grep -E  'd4.*+/-' gnufit_$f-ex | awk '{print "a'$f'_4e =", $3}' >> Parameters-ex.dat

echo "$f ex DONE"

done

##dir neg
for f in 14 16 18 23 25 27 36 38 45 47 56 58 67 78 

do 

cat > make_fit_$f-dir <<EOF
set encoding utf8
set terminal postscript eps enhanced color solid "Times-Roman" 20
set output 'Fit-D$f-dir.eps'

FIT_LIMIT=1.0e-18

set xrange [0.999998e-9:3.0000001e-9]
set yrange [0.999998e-9:3.0000001e-9]
#set zrange [1e-6:*]

set logscale z

d2=1
d3=2
d4=2

f4(x,y) =  d1+(d2/((x*10**9)**d3*(y*10**9)**d4))

fit f4(x,y) 'D$f-dir.dat' u (\$1):(\$2):(abs(\$3)) via d1,d2,d3,d4

splot 'D$f-dir.dat' u (\$1):(\$2):(abs(\$3)) w l lw 3 t 'Theo.',  \
f4(x,y) w l t 'Fit'

EOF

gnuplot make_fit_$f-dir 2> gnufit_$f-dir

grep -E  'd1.*+/-' gnufit_$f-dir | awk '{print "a'$f'_1e =", $3}' >> Parameters-dir.dat 
grep -E  'd2.*+/-' gnufit_$f-dir | awk '{print "a'$f'_2e =", $3}' >> Parameters-dir.dat 
grep -E  'd3.*+/-' gnufit_$f-dir | awk '{print "a'$f'_3e =", $3}' >> Parameters-dir.dat 
grep -E  'd4.*+/-' gnufit_$f-dir | awk '{print "a'$f'_4e =", $3}' >> Parameters-dir.dat

echo "$f dir DONE"

done

##exc neg
for f in 14 16 18 23 25 27 36 38 45 47 56 58 67 78 

do 

cat > make_fit_$f-ex <<EOF
set encoding utf8
set terminal postscript eps enhanced color solid "Times-Roman" 20
set output 'Fit-D$f-ex.eps'

FIT_LIMIT=1.0e-18

set xrange [0.999998e-9:3.0000001e-9]
set yrange [0.999998e-9:3.0000001e-9]
#set zrange [1e-6:*]

set logscale z

d2=1
d3=2
d4=2

f4(x,y) =  d1+(d2/((x*10**9)**d3*(y*10**9)**d4))

fit f4(x,y) 'D$f-ex.dat' u (\$1):(\$2):(abs(\$3)) via d1,d2,d3,d4

splot 'D$f-ex.dat' u (\$1):(\$2):(abs(\$3)) w l lw 3 t 'Theo.',  \
f4(x,y) w l t 'Fit'

EOF

gnuplot make_fit_$f-ex 2> gnufit_$f-ex

grep -E  'd1.*+/-' gnufit_$f-ex | awk '{print "a'$f'_1e =", $3}' >> Parameters-ex.dat 
grep -E  'd2.*+/-' gnufit_$f-ex | awk '{print "a'$f'_2e =", $3}' >> Parameters-ex.dat 
grep -E  'd3.*+/-' gnufit_$f-ex | awk '{print "a'$f'_3e =", $3}' >> Parameters-ex.dat 
grep -E  'd4.*+/-' gnufit_$f-ex | awk '{print "a'$f'_4e =", $3}' >> Parameters-ex.dat

echo "$f ex DONE"

done
